# Generated by Django 3.2.14 on 2022-11-20 17:46

from django.db import migrations, models
import orders.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(choices=[('Margherita', 'Margherita'), ('Prosciutto Crudo', 'Prosciutto Crudo'), ('Quattro Formaggi', 'Quattro Formaggi'), ('Hawaii', 'Hawaii'), ('Diavola', 'Diavola'), ('Tuna', 'Tuna')], max_length=50)),
                ('ordered_at', models.BigIntegerField(default=orders.utils.now_timestamp)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
